version: 2.1
jobs:
  build:
    docker: &image
      - image: circleci/openjdk:11-jdk
    steps:
      - run: &env
          name: Set environment
          command: |
            echo "export DISABLE_DOWNLOAD_PROGRESS_OPTS=-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn" >> $BASH_ENV
            echo "export LINUX_MVN_RANDOM=-Djava.security.egd=file:/dev/./urandom" >> $BASH_ENV
            source $BASH_ENV
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Full build. Includes testing and static analysis. Does not include release tasks.
          command: mvn install --batch-mode $DISABLE_DOWNLOAD_PROGRESS_OPTS
      - store_artifacts:
          path: target
          destination: owasp_report
      - save_cache:
          paths:
           - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: .
          paths:
            - "**"
workflows:
  version: 2.1
  default:
    jobs:
      - build:
          context: secrets
